### ISSUE TITLE
Некорректная работа Ergo.data.Collection

### ISSUE THREAD

**Issue by Able1991** [eliace/ergo-js#33]
http://jsfiddle.net/1yb2y7hb/

Не работает фабрика дочерних элементов и инизиализатор дочернего класса(видимо он не прицепляется)

**Comment by eliace** [comment]
Фабрика работает, но элемент будет создан только при первом обращении или обходе ("ленивая" инициализация). Если есть необходимость, можно добавить в DataSource и "жадную" инициализацию
