### ISSUE TITLE
Ошибка в "async-select"

### ISSUE THREAD

**Issue by vvnab** [eliace/ergo-js#34]
Ошибка в __async-select__ при использовании с __input__ (для фильтрации списка) в случае с множественным __dataId__.
Проявляется только после __.fetch()__. При выборе из начального списка всё ОК.

```
Uncaught TypeError: Cannot use 'in' operator to search for '..id' in ...
Ergo.declare._val @ ergojs-core.js:2855
Ergo.declare.set @ ergojs-core.js:2991
value @ ergojs-core.js:7126
Ergo.defineClass._opt @ ergojs-core.js:7301
...
```

**Comment by eliace** [comment]
Внесены исправления и добавлен пример
