### ISSUE TITLE
Ширина виджета в firefox

### ISSUE THREAD

**Issue by Able1991** [eliace/ergo-js#37]
В лисе есть баг у метода jquery.width(), при задании ширины в процентах, к итоговой ширине он прибавляет значения боковых паддингов(при box-sizing: border-box;)
В итоге виджет с классом padding и шириной 30% получает итоговую ширину 48,3 %
http://jsfiddle.net/5ggsfnfn/

**Comment by Able1991** [comment]
Возможно, если у виджета есть box-sizing: border-box, необходимо вызывать метод outerWidth() ?

**Comment by eliace** [comment]
да. уже поменял
