### ISSUE TITLE
Работа с динамическим фильтром данных

### ISSUE THREAD

**Issue by Able1991** [eliace/ergo-js#38]
Если виджету указать dynamicFilter, после привязки данных невозможно получить результат фильтрации.
Кейсы: 
1. Скрыть список если не одна из записей в данных не прошла фильтрацию.
2. В заголовок списка вывести количество элементов в списке

**Comment by eliace** [comment]
Можно воспользоваться списком элементов `this.items`. Теперь обновление происходит после того как был применен фильтр, поэтому в списке будет правильное количество элементов.

**Comment by Able1991** [comment]
Если менять данные через set(), это не срабатывает
http://jsfiddle.net/9zjLwab2/

**Comment by eliace** [comment]
Для динамически связанных виджетов было отключено обновление через `_rebind`. Теперь включено обратно
