### ISSUE TITLE
Некорректно работает примесь selectable в режиме multiselect

### ISSUE THREAD

**Issue by Able1991** [eliace/ergo-js#42]
http://jsfiddle.net/v2qpLhpc/

Возможно неправильно работает Ergo.remove(this._selected, unselected);

**Comment by eliace** [comment]
Да. Ошибка в Ergo.remove(). Исправлено.

**Comment by Able1991** [comment]
Все равно проблемы.
Ставлю первому
Ставлю второму
Снимаю первому
Снимаю второму =>  .selection.get() => [<1 элемент>]

**Comment by eliace** [comment]
Изменена работа методов `selection`. `selection.get()` при `multiselect` возвращает объект, ключами которого являются ключи поиска, а значением - выбранный виджет. Также есть вариант с `selection.get(key)`, который возвращает выбранный объект по ключу.
Кроме того, оказалось, что `ergo.remove()` было исправлено не полностью. Теперь все ошибки устранены.
