### ISSUE TITLE
Составной ключ данных работает некорректно

### ISSUE THREAD

**Issue by Able1991** [eliace/ergo-js#44]
http://jsfiddle.net/fL9r9jm2/

При изменении данных не срабатывает биндинг на виджете с составным ключем

**Comment by eliace** [comment]
Изменена работа составного ключа. Теперь создается не отдельный дочерний источник данных, а комбинируются существующие. Получается, что два виджета связанные простым и составным ключом фактически связаны с одним источником данных

**Comment by Able1991** [comment]
http://jsfiddle.net/fL9r9jm2/1/
В примере проблема не решилась

**Comment by eliace** [comment]
Теперь работает
