### ISSUE TITLE
Переключение состояний через includes:router

### ISSUE THREAD

**Issue by Able1991** [eliace/ergo-js#47]
Из за отсутствия возможности передавать параметры через $context.to хотелось бы получать дополнительную возможность взаимодействия с итоговым scope, например так:
```
$context.to('/some_url').then(function(scope) {
  scope.events.rise('someEvent')
});
```
Но еще лучше было бы добавить возможность отправлять параметры, причем разных видов. Те которые сохраняются как query param в history и простые "разовые".
```
$context.to("/some_url",{params:{$a:1,b:2}})
....
$context.scope('some_scope', function($scope, $params) {
   $params // => {$a:1,b:2} 
})
```

Кейс: Есть глобальынй тулбокс, из которого мы хотип попасть на определенную страницу и запустить на ней какой то процесс / событие

**Comment by eliace** [comment]
Теперь $context.to(path, params, options) возвращает Promise и принимает вторым аргументом параметры маршрута, а третьим опции скоупа. Вопрос о сохранении/извлечении параметров запроса остается открытым
