### ISSUE TITLE
Ошибка в dynamicSorter при синхронизации данных

### ISSUE THREAD

**Issue by Able1991** [eliace/ergo-js#50]
в сортер попадают параметры undefined

![Ошибка](https://hsto.org/files/1ac/3ee/414/1ac3ee414a3f4ccfa5561dd2bb819475.PNG)

**Comment by eliace** [comment]
Проблема все еще есть?

**Comment by Able1991** [comment]
да, появлялись виджеты с undefined данными и падала сортировка

**Comment by Able1991** [comment]
Вот пример с большими json
http://jsfiddle.net/0no6dve2/5/

**Comment by eliace** [comment]
В примере ошибки не возникает

**Comment by Able1991** [comment]
![Ошибка](https://hsto.org/files/060/ed7/63e/060ed763ec534cd4aa4e48881d71fdae.PNG)

**Comment by eliace** [comment]
![printscreen2](https://cloud.githubusercontent.com/assets/281135/11085416/30848b62-8857-11e5-884a-03cfeec96fb6.PNG)
Что я делаю не так?

**Comment by Able1991** [comment]
Хм, видимо пользуешься мозилой =\

**Comment by eliace** [comment]
Ошибка исправлена
