### ISSUE TITLE
Некорректная работа selection

### ISSUE THREAD

**Issue by Able1991** [eliace/ergo-js#57]
selection.get возвращает пустой массив если selection не multiple, думаю должен null возвращать

**Comment by eliace** [comment]
А можно пример?

**Comment by Able1991** [comment]
http://jsfiddle.net/0no6dve2/8/
Проблема после вызова .clear()
Если ничего не выделено то эксепшен
Если что то выделено то selection.get() вовращает пустой массив, и дальше ничего уже не выделить

**Comment by eliace** [comment]
Исправлено
