### ISSUE TITLE
Контекст dynamicFilter и dynamicSorter

### ISSUE THREAD

**Issue by Able1991** [eliace/ergo-js#59]
Котекстом вызова функций должен быть виджет

**Comment by eliace** [comment]
Так понимаю, это для того, чтобы управлять параметрами фильтрации и сортировки с помощью опций виджета?

**Comment by Able1991** [comment]
Да, ну и не совсем очевидно что у функции являющейся опцией виджета иной контекст.
В принципе, задача решаеться использованием renderFilter, так что проблема не критична.

**Comment by eliace** [comment]
Сейчас контекстом dynamicFilter и dynamicSorter является DataSource. Так понимаю, это неудобно?

**Comment by eliace** [comment]
Контекст изменен
